//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGNoTeam_V5.MonitoreoOrdenesWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", ConfigurationName="MonitoreoOrdenesWS.MonitorOrdenWS")]
    public interface MonitorOrdenWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/insertarEjecucionRequest", ReplyAction="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/insertarEjecucionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GGNoTeam_V5.MonitoreoOrdenesWS.insertarEjecucionResponse insertarEjecucion(GGNoTeam_V5.MonitoreoOrdenesWS.insertarEjecucionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/insertarEjecucionRequest", ReplyAction="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/insertarEjecucionResponse")]
        System.Threading.Tasks.Task<GGNoTeam_V5.MonitoreoOrdenesWS.insertarEjecucionResponse> insertarEjecucionAsync(GGNoTeam_V5.MonitoreoOrdenesWS.insertarEjecucionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/eliminarEjecucionRequest", ReplyAction="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/eliminarEjecucionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GGNoTeam_V5.MonitoreoOrdenesWS.eliminarEjecucionResponse eliminarEjecucion(GGNoTeam_V5.MonitoreoOrdenesWS.eliminarEjecucionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/eliminarEjecucionRequest", ReplyAction="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/eliminarEjecucionResponse")]
        System.Threading.Tasks.Task<GGNoTeam_V5.MonitoreoOrdenesWS.eliminarEjecucionResponse> eliminarEjecucionAsync(GGNoTeam_V5.MonitoreoOrdenesWS.eliminarEjecucionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/ListarEjecucionPorFechaReques" +
            "t", ReplyAction="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/ListarEjecucionPorFechaRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GGNoTeam_V5.MonitoreoOrdenesWS.ListarEjecucionPorFechaResponse ListarEjecucionPorFecha(GGNoTeam_V5.MonitoreoOrdenesWS.ListarEjecucionPorFechaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/ListarEjecucionPorFechaReques" +
            "t", ReplyAction="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/ListarEjecucionPorFechaRespon" +
            "se")]
        System.Threading.Tasks.Task<GGNoTeam_V5.MonitoreoOrdenesWS.ListarEjecucionPorFechaResponse> ListarEjecucionPorFechaAsync(GGNoTeam_V5.MonitoreoOrdenesWS.ListarEjecucionPorFechaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/listarTodosEjecucionRequest", ReplyAction="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/listarTodosEjecucionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GGNoTeam_V5.MonitoreoOrdenesWS.listarTodosEjecucionResponse listarTodosEjecucion(GGNoTeam_V5.MonitoreoOrdenesWS.listarTodosEjecucionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/listarTodosEjecucionRequest", ReplyAction="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/listarTodosEjecucionResponse")]
        System.Threading.Tasks.Task<GGNoTeam_V5.MonitoreoOrdenesWS.listarTodosEjecucionResponse> listarTodosEjecucionAsync(GGNoTeam_V5.MonitoreoOrdenesWS.listarTodosEjecucionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/modificarEjecucionRequest", ReplyAction="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/modificarEjecucionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GGNoTeam_V5.MonitoreoOrdenesWS.modificarEjecucionResponse modificarEjecucion(GGNoTeam_V5.MonitoreoOrdenesWS.modificarEjecucionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/modificarEjecucionRequest", ReplyAction="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/modificarEjecucionResponse")]
        System.Threading.Tasks.Task<GGNoTeam_V5.MonitoreoOrdenesWS.modificarEjecucionResponse> modificarEjecucionAsync(GGNoTeam_V5.MonitoreoOrdenesWS.modificarEjecucionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/eliminarOperacionRequest", ReplyAction="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/eliminarOperacionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GGNoTeam_V5.MonitoreoOrdenesWS.eliminarOperacionResponse eliminarOperacion(GGNoTeam_V5.MonitoreoOrdenesWS.eliminarOperacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/eliminarOperacionRequest", ReplyAction="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/eliminarOperacionResponse")]
        System.Threading.Tasks.Task<GGNoTeam_V5.MonitoreoOrdenesWS.eliminarOperacionResponse> eliminarOperacionAsync(GGNoTeam_V5.MonitoreoOrdenesWS.eliminarOperacionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/")]
    public partial class ejecucion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double aUMField;
        
        private int activoField;
        
        private eAsset assetclassField;
        
        private bool assetclassFieldSpecified;
        
        private double cantInstrOrdenField;
        
        private double cantidadField;
        
        private string codisinField;
        
        private string codsbsField;
        
        private double comisionField;
        
        private string estadoField;
        
        private System.DateTime fechaLiqField;
        
        private bool fechaLiqFieldSpecified;
        
        private System.DateTime fechaOperField;
        
        private bool fechaOperFieldSpecified;
        
        private eTipoFondo fondoField;
        
        private bool fondoFieldSpecified;
        
        private string horaRegistroField;
        
        private int idEjecucionField;
        
        private string instrumentoField;
        
        private string intermediarioField;
        
        private string medioNegociacionField;
        
        private double precioField;
        
        private double pxqField;
        
        private double pxqsolesField;
        
        private string tipoCondField;
        
        private eTipoMoneda tipoMonedaField;
        
        private bool tipoMonedaFieldSpecified;
        
        private eTipoOperacion tipoOperField;
        
        private bool tipoOperFieldSpecified;
        
        private System.DateTime fCompraAntiguaField;
        
        private bool fCompraAntiguaFieldSpecified;
        
        private System.DateTime fCompraRecienteField;
        
        private bool fCompraRecienteFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double AUM {
            get {
                return this.aUMField;
            }
            set {
                this.aUMField = value;
                this.RaisePropertyChanged("AUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public eAsset assetclass {
            get {
                return this.assetclassField;
            }
            set {
                this.assetclassField = value;
                this.RaisePropertyChanged("assetclass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool assetclassSpecified {
            get {
                return this.assetclassFieldSpecified;
            }
            set {
                this.assetclassFieldSpecified = value;
                this.RaisePropertyChanged("assetclassSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double cantInstrOrden {
            get {
                return this.cantInstrOrdenField;
            }
            set {
                this.cantInstrOrdenField = value;
                this.RaisePropertyChanged("cantInstrOrden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string codisin {
            get {
                return this.codisinField;
            }
            set {
                this.codisinField = value;
                this.RaisePropertyChanged("codisin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string codsbs {
            get {
                return this.codsbsField;
            }
            set {
                this.codsbsField = value;
                this.RaisePropertyChanged("codsbs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double comision {
            get {
                return this.comisionField;
            }
            set {
                this.comisionField = value;
                this.RaisePropertyChanged("comision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public System.DateTime fechaLiq {
            get {
                return this.fechaLiqField;
            }
            set {
                this.fechaLiqField = value;
                this.RaisePropertyChanged("fechaLiq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaLiqSpecified {
            get {
                return this.fechaLiqFieldSpecified;
            }
            set {
                this.fechaLiqFieldSpecified = value;
                this.RaisePropertyChanged("fechaLiqSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public System.DateTime fechaOper {
            get {
                return this.fechaOperField;
            }
            set {
                this.fechaOperField = value;
                this.RaisePropertyChanged("fechaOper");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaOperSpecified {
            get {
                return this.fechaOperFieldSpecified;
            }
            set {
                this.fechaOperFieldSpecified = value;
                this.RaisePropertyChanged("fechaOperSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public eTipoFondo fondo {
            get {
                return this.fondoField;
            }
            set {
                this.fondoField = value;
                this.RaisePropertyChanged("fondo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fondoSpecified {
            get {
                return this.fondoFieldSpecified;
            }
            set {
                this.fondoFieldSpecified = value;
                this.RaisePropertyChanged("fondoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string horaRegistro {
            get {
                return this.horaRegistroField;
            }
            set {
                this.horaRegistroField = value;
                this.RaisePropertyChanged("horaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public int idEjecucion {
            get {
                return this.idEjecucionField;
            }
            set {
                this.idEjecucionField = value;
                this.RaisePropertyChanged("idEjecucion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string instrumento {
            get {
                return this.instrumentoField;
            }
            set {
                this.instrumentoField = value;
                this.RaisePropertyChanged("instrumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string intermediario {
            get {
                return this.intermediarioField;
            }
            set {
                this.intermediarioField = value;
                this.RaisePropertyChanged("intermediario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string medioNegociacion {
            get {
                return this.medioNegociacionField;
            }
            set {
                this.medioNegociacionField = value;
                this.RaisePropertyChanged("medioNegociacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public double pxq {
            get {
                return this.pxqField;
            }
            set {
                this.pxqField = value;
                this.RaisePropertyChanged("pxq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public double pxqsoles {
            get {
                return this.pxqsolesField;
            }
            set {
                this.pxqsolesField = value;
                this.RaisePropertyChanged("pxqsoles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string tipoCond {
            get {
                return this.tipoCondField;
            }
            set {
                this.tipoCondField = value;
                this.RaisePropertyChanged("tipoCond");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public eTipoMoneda tipoMoneda {
            get {
                return this.tipoMonedaField;
            }
            set {
                this.tipoMonedaField = value;
                this.RaisePropertyChanged("tipoMoneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoMonedaSpecified {
            get {
                return this.tipoMonedaFieldSpecified;
            }
            set {
                this.tipoMonedaFieldSpecified = value;
                this.RaisePropertyChanged("tipoMonedaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public eTipoOperacion tipoOper {
            get {
                return this.tipoOperField;
            }
            set {
                this.tipoOperField = value;
                this.RaisePropertyChanged("tipoOper");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoOperSpecified {
            get {
                return this.tipoOperFieldSpecified;
            }
            set {
                this.tipoOperFieldSpecified = value;
                this.RaisePropertyChanged("tipoOperSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public System.DateTime fCompraAntigua {
            get {
                return this.fCompraAntiguaField;
            }
            set {
                this.fCompraAntiguaField = value;
                this.RaisePropertyChanged("fCompraAntigua");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fCompraAntiguaSpecified {
            get {
                return this.fCompraAntiguaFieldSpecified;
            }
            set {
                this.fCompraAntiguaFieldSpecified = value;
                this.RaisePropertyChanged("fCompraAntiguaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public System.DateTime fCompraReciente {
            get {
                return this.fCompraRecienteField;
            }
            set {
                this.fCompraRecienteField = value;
                this.RaisePropertyChanged("fCompraReciente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fCompraRecienteSpecified {
            get {
                return this.fCompraRecienteFieldSpecified;
            }
            set {
                this.fCompraRecienteFieldSpecified = value;
                this.RaisePropertyChanged("fCompraRecienteSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/")]
    public enum eAsset {
        
        /// <remarks/>
        Renta_Fija,
        
        /// <remarks/>
        Renta_Variable,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/")]
    public enum eTipoFondo {
        
        /// <remarks/>
        Fondo1,
        
        /// <remarks/>
        Fondo2,
        
        /// <remarks/>
        Fondo3,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/")]
    public enum eTipoMoneda {
        
        /// <remarks/>
        AUD,
        
        /// <remarks/>
        BRL,
        
        /// <remarks/>
        CAD,
        
        /// <remarks/>
        CHF,
        
        /// <remarks/>
        CLP,
        
        /// <remarks/>
        CNH,
        
        /// <remarks/>
        CNY,
        
        /// <remarks/>
        COP,
        
        /// <remarks/>
        CZK,
        
        /// <remarks/>
        DKK,
        
        /// <remarks/>
        USD,
        
        /// <remarks/>
        EGP,
        
        /// <remarks/>
        EUR,
        
        /// <remarks/>
        GBP,
        
        /// <remarks/>
        HKD,
        
        /// <remarks/>
        HUF,
        
        /// <remarks/>
        IDR,
        
        /// <remarks/>
        ILS,
        
        /// <remarks/>
        INR,
        
        /// <remarks/>
        JPY,
        
        /// <remarks/>
        KRW,
        
        /// <remarks/>
        MXN,
        
        /// <remarks/>
        NOK,
        
        /// <remarks/>
        PEN,
        
        /// <remarks/>
        NZD,
        
        /// <remarks/>
        PLN,
        
        /// <remarks/>
        RON,
        
        /// <remarks/>
        RUB,
        
        /// <remarks/>
        SEK,
        
        /// <remarks/>
        SGD,
        
        /// <remarks/>
        THB,
        
        /// <remarks/>
        TRY,
        
        /// <remarks/>
        TWD,
        
        /// <remarks/>
        noRegistrado,
        
        /// <remarks/>
        ZAR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/")]
    public enum eTipoOperacion {
        
        /// <remarks/>
        compra,
        
        /// <remarks/>
        venta,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEjecucion", WrapperNamespace="http://webservices.sist.afp.ggNoTeam/", IsWrapped=true)]
    public partial class insertarEjecucionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GGNoTeam_V5.MonitoreoOrdenesWS.ejecucion Ejecucion;
        
        public insertarEjecucionRequest() {
        }
        
        public insertarEjecucionRequest(GGNoTeam_V5.MonitoreoOrdenesWS.ejecucion Ejecucion) {
            this.Ejecucion = Ejecucion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEjecucionResponse", WrapperNamespace="http://webservices.sist.afp.ggNoTeam/", IsWrapped=true)]
    public partial class insertarEjecucionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarEjecucionResponse() {
        }
        
        public insertarEjecucionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEjecucion", WrapperNamespace="http://webservices.sist.afp.ggNoTeam/", IsWrapped=true)]
    public partial class eliminarEjecucionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEjecucion;
        
        public eliminarEjecucionRequest() {
        }
        
        public eliminarEjecucionRequest(int idEjecucion) {
            this.idEjecucion = idEjecucion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEjecucionResponse", WrapperNamespace="http://webservices.sist.afp.ggNoTeam/", IsWrapped=true)]
    public partial class eliminarEjecucionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarEjecucionResponse() {
        }
        
        public eliminarEjecucionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarEjecucionPorFecha", WrapperNamespace="http://webservices.sist.afp.ggNoTeam/", IsWrapped=true)]
    public partial class ListarEjecucionPorFechaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaIni;
        
        public ListarEjecucionPorFechaRequest() {
        }
        
        public ListarEjecucionPorFechaRequest(string fechaIni) {
            this.fechaIni = fechaIni;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarEjecucionPorFechaResponse", WrapperNamespace="http://webservices.sist.afp.ggNoTeam/", IsWrapped=true)]
    public partial class ListarEjecucionPorFechaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GGNoTeam_V5.MonitoreoOrdenesWS.ejecucion[] @return;
        
        public ListarEjecucionPorFechaResponse() {
        }
        
        public ListarEjecucionPorFechaResponse(GGNoTeam_V5.MonitoreoOrdenesWS.ejecucion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosEjecucion", WrapperNamespace="http://webservices.sist.afp.ggNoTeam/", IsWrapped=true)]
    public partial class listarTodosEjecucionRequest {
        
        public listarTodosEjecucionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosEjecucionResponse", WrapperNamespace="http://webservices.sist.afp.ggNoTeam/", IsWrapped=true)]
    public partial class listarTodosEjecucionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GGNoTeam_V5.MonitoreoOrdenesWS.ejecucion[] @return;
        
        public listarTodosEjecucionResponse() {
        }
        
        public listarTodosEjecucionResponse(GGNoTeam_V5.MonitoreoOrdenesWS.ejecucion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarEjecucion", WrapperNamespace="http://webservices.sist.afp.ggNoTeam/", IsWrapped=true)]
    public partial class modificarEjecucionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GGNoTeam_V5.MonitoreoOrdenesWS.ejecucion Ejecucion;
        
        public modificarEjecucionRequest() {
        }
        
        public modificarEjecucionRequest(GGNoTeam_V5.MonitoreoOrdenesWS.ejecucion Ejecucion) {
            this.Ejecucion = Ejecucion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarEjecucionResponse", WrapperNamespace="http://webservices.sist.afp.ggNoTeam/", IsWrapped=true)]
    public partial class modificarEjecucionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarEjecucionResponse() {
        }
        
        public modificarEjecucionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarOperacion", WrapperNamespace="http://webservices.sist.afp.ggNoTeam/", IsWrapped=true)]
    public partial class eliminarOperacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idOperacion;
        
        public eliminarOperacionRequest() {
        }
        
        public eliminarOperacionRequest(int idOperacion) {
            this.idOperacion = idOperacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarOperacionResponse", WrapperNamespace="http://webservices.sist.afp.ggNoTeam/", IsWrapped=true)]
    public partial class eliminarOperacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarOperacionResponse() {
        }
        
        public eliminarOperacionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MonitorOrdenWSChannel : GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonitorOrdenWSClient : System.ServiceModel.ClientBase<GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS>, GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS {
        
        public MonitorOrdenWSClient() {
        }
        
        public MonitorOrdenWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonitorOrdenWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorOrdenWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorOrdenWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GGNoTeam_V5.MonitoreoOrdenesWS.insertarEjecucionResponse GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS.insertarEjecucion(GGNoTeam_V5.MonitoreoOrdenesWS.insertarEjecucionRequest request) {
            return base.Channel.insertarEjecucion(request);
        }
        
        public int insertarEjecucion(GGNoTeam_V5.MonitoreoOrdenesWS.ejecucion Ejecucion) {
            GGNoTeam_V5.MonitoreoOrdenesWS.insertarEjecucionRequest inValue = new GGNoTeam_V5.MonitoreoOrdenesWS.insertarEjecucionRequest();
            inValue.Ejecucion = Ejecucion;
            GGNoTeam_V5.MonitoreoOrdenesWS.insertarEjecucionResponse retVal = ((GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS)(this)).insertarEjecucion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GGNoTeam_V5.MonitoreoOrdenesWS.insertarEjecucionResponse> GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS.insertarEjecucionAsync(GGNoTeam_V5.MonitoreoOrdenesWS.insertarEjecucionRequest request) {
            return base.Channel.insertarEjecucionAsync(request);
        }
        
        public System.Threading.Tasks.Task<GGNoTeam_V5.MonitoreoOrdenesWS.insertarEjecucionResponse> insertarEjecucionAsync(GGNoTeam_V5.MonitoreoOrdenesWS.ejecucion Ejecucion) {
            GGNoTeam_V5.MonitoreoOrdenesWS.insertarEjecucionRequest inValue = new GGNoTeam_V5.MonitoreoOrdenesWS.insertarEjecucionRequest();
            inValue.Ejecucion = Ejecucion;
            return ((GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS)(this)).insertarEjecucionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GGNoTeam_V5.MonitoreoOrdenesWS.eliminarEjecucionResponse GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS.eliminarEjecucion(GGNoTeam_V5.MonitoreoOrdenesWS.eliminarEjecucionRequest request) {
            return base.Channel.eliminarEjecucion(request);
        }
        
        public int eliminarEjecucion(int idEjecucion) {
            GGNoTeam_V5.MonitoreoOrdenesWS.eliminarEjecucionRequest inValue = new GGNoTeam_V5.MonitoreoOrdenesWS.eliminarEjecucionRequest();
            inValue.idEjecucion = idEjecucion;
            GGNoTeam_V5.MonitoreoOrdenesWS.eliminarEjecucionResponse retVal = ((GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS)(this)).eliminarEjecucion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GGNoTeam_V5.MonitoreoOrdenesWS.eliminarEjecucionResponse> GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS.eliminarEjecucionAsync(GGNoTeam_V5.MonitoreoOrdenesWS.eliminarEjecucionRequest request) {
            return base.Channel.eliminarEjecucionAsync(request);
        }
        
        public System.Threading.Tasks.Task<GGNoTeam_V5.MonitoreoOrdenesWS.eliminarEjecucionResponse> eliminarEjecucionAsync(int idEjecucion) {
            GGNoTeam_V5.MonitoreoOrdenesWS.eliminarEjecucionRequest inValue = new GGNoTeam_V5.MonitoreoOrdenesWS.eliminarEjecucionRequest();
            inValue.idEjecucion = idEjecucion;
            return ((GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS)(this)).eliminarEjecucionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GGNoTeam_V5.MonitoreoOrdenesWS.ListarEjecucionPorFechaResponse GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS.ListarEjecucionPorFecha(GGNoTeam_V5.MonitoreoOrdenesWS.ListarEjecucionPorFechaRequest request) {
            return base.Channel.ListarEjecucionPorFecha(request);
        }
        
        public GGNoTeam_V5.MonitoreoOrdenesWS.ejecucion[] ListarEjecucionPorFecha(string fechaIni) {
            GGNoTeam_V5.MonitoreoOrdenesWS.ListarEjecucionPorFechaRequest inValue = new GGNoTeam_V5.MonitoreoOrdenesWS.ListarEjecucionPorFechaRequest();
            inValue.fechaIni = fechaIni;
            GGNoTeam_V5.MonitoreoOrdenesWS.ListarEjecucionPorFechaResponse retVal = ((GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS)(this)).ListarEjecucionPorFecha(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GGNoTeam_V5.MonitoreoOrdenesWS.ListarEjecucionPorFechaResponse> GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS.ListarEjecucionPorFechaAsync(GGNoTeam_V5.MonitoreoOrdenesWS.ListarEjecucionPorFechaRequest request) {
            return base.Channel.ListarEjecucionPorFechaAsync(request);
        }
        
        public System.Threading.Tasks.Task<GGNoTeam_V5.MonitoreoOrdenesWS.ListarEjecucionPorFechaResponse> ListarEjecucionPorFechaAsync(string fechaIni) {
            GGNoTeam_V5.MonitoreoOrdenesWS.ListarEjecucionPorFechaRequest inValue = new GGNoTeam_V5.MonitoreoOrdenesWS.ListarEjecucionPorFechaRequest();
            inValue.fechaIni = fechaIni;
            return ((GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS)(this)).ListarEjecucionPorFechaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GGNoTeam_V5.MonitoreoOrdenesWS.listarTodosEjecucionResponse GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS.listarTodosEjecucion(GGNoTeam_V5.MonitoreoOrdenesWS.listarTodosEjecucionRequest request) {
            return base.Channel.listarTodosEjecucion(request);
        }
        
        public GGNoTeam_V5.MonitoreoOrdenesWS.ejecucion[] listarTodosEjecucion() {
            GGNoTeam_V5.MonitoreoOrdenesWS.listarTodosEjecucionRequest inValue = new GGNoTeam_V5.MonitoreoOrdenesWS.listarTodosEjecucionRequest();
            GGNoTeam_V5.MonitoreoOrdenesWS.listarTodosEjecucionResponse retVal = ((GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS)(this)).listarTodosEjecucion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GGNoTeam_V5.MonitoreoOrdenesWS.listarTodosEjecucionResponse> GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS.listarTodosEjecucionAsync(GGNoTeam_V5.MonitoreoOrdenesWS.listarTodosEjecucionRequest request) {
            return base.Channel.listarTodosEjecucionAsync(request);
        }
        
        public System.Threading.Tasks.Task<GGNoTeam_V5.MonitoreoOrdenesWS.listarTodosEjecucionResponse> listarTodosEjecucionAsync() {
            GGNoTeam_V5.MonitoreoOrdenesWS.listarTodosEjecucionRequest inValue = new GGNoTeam_V5.MonitoreoOrdenesWS.listarTodosEjecucionRequest();
            return ((GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS)(this)).listarTodosEjecucionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GGNoTeam_V5.MonitoreoOrdenesWS.modificarEjecucionResponse GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS.modificarEjecucion(GGNoTeam_V5.MonitoreoOrdenesWS.modificarEjecucionRequest request) {
            return base.Channel.modificarEjecucion(request);
        }
        
        public int modificarEjecucion(GGNoTeam_V5.MonitoreoOrdenesWS.ejecucion Ejecucion) {
            GGNoTeam_V5.MonitoreoOrdenesWS.modificarEjecucionRequest inValue = new GGNoTeam_V5.MonitoreoOrdenesWS.modificarEjecucionRequest();
            inValue.Ejecucion = Ejecucion;
            GGNoTeam_V5.MonitoreoOrdenesWS.modificarEjecucionResponse retVal = ((GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS)(this)).modificarEjecucion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GGNoTeam_V5.MonitoreoOrdenesWS.modificarEjecucionResponse> GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS.modificarEjecucionAsync(GGNoTeam_V5.MonitoreoOrdenesWS.modificarEjecucionRequest request) {
            return base.Channel.modificarEjecucionAsync(request);
        }
        
        public System.Threading.Tasks.Task<GGNoTeam_V5.MonitoreoOrdenesWS.modificarEjecucionResponse> modificarEjecucionAsync(GGNoTeam_V5.MonitoreoOrdenesWS.ejecucion Ejecucion) {
            GGNoTeam_V5.MonitoreoOrdenesWS.modificarEjecucionRequest inValue = new GGNoTeam_V5.MonitoreoOrdenesWS.modificarEjecucionRequest();
            inValue.Ejecucion = Ejecucion;
            return ((GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS)(this)).modificarEjecucionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GGNoTeam_V5.MonitoreoOrdenesWS.eliminarOperacionResponse GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS.eliminarOperacion(GGNoTeam_V5.MonitoreoOrdenesWS.eliminarOperacionRequest request) {
            return base.Channel.eliminarOperacion(request);
        }
        
        public int eliminarOperacion(int idOperacion) {
            GGNoTeam_V5.MonitoreoOrdenesWS.eliminarOperacionRequest inValue = new GGNoTeam_V5.MonitoreoOrdenesWS.eliminarOperacionRequest();
            inValue.idOperacion = idOperacion;
            GGNoTeam_V5.MonitoreoOrdenesWS.eliminarOperacionResponse retVal = ((GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS)(this)).eliminarOperacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GGNoTeam_V5.MonitoreoOrdenesWS.eliminarOperacionResponse> GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS.eliminarOperacionAsync(GGNoTeam_V5.MonitoreoOrdenesWS.eliminarOperacionRequest request) {
            return base.Channel.eliminarOperacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<GGNoTeam_V5.MonitoreoOrdenesWS.eliminarOperacionResponse> eliminarOperacionAsync(int idOperacion) {
            GGNoTeam_V5.MonitoreoOrdenesWS.eliminarOperacionRequest inValue = new GGNoTeam_V5.MonitoreoOrdenesWS.eliminarOperacionRequest();
            inValue.idOperacion = idOperacion;
            return ((GGNoTeam_V5.MonitoreoOrdenesWS.MonitorOrdenWS)(this)).eliminarOperacionAsync(inValue);
        }
    }
}
