//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGNoTeam_V5.AccionesWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", ConfigurationName="AccionesWS.AccionesWS")]
    public interface AccionesWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sist.afp.ggNoTeam/AccionesWS/insertarAccionRequest", ReplyAction="http://webservices.sist.afp.ggNoTeam/AccionesWS/insertarAccionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GGNoTeam_V5.AccionesWS.insertarAccionResponse insertarAccion(GGNoTeam_V5.AccionesWS.insertarAccionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sist.afp.ggNoTeam/AccionesWS/insertarAccionRequest", ReplyAction="http://webservices.sist.afp.ggNoTeam/AccionesWS/insertarAccionResponse")]
        System.Threading.Tasks.Task<GGNoTeam_V5.AccionesWS.insertarAccionResponse> insertarAccionAsync(GGNoTeam_V5.AccionesWS.insertarAccionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sist.afp.ggNoTeam/AccionesWS/listarAccionesPorFechasRequest", ReplyAction="http://webservices.sist.afp.ggNoTeam/AccionesWS/listarAccionesPorFechasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GGNoTeam_V5.AccionesWS.listarAccionesPorFechasResponse listarAccionesPorFechas(GGNoTeam_V5.AccionesWS.listarAccionesPorFechasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sist.afp.ggNoTeam/AccionesWS/listarAccionesPorFechasRequest", ReplyAction="http://webservices.sist.afp.ggNoTeam/AccionesWS/listarAccionesPorFechasResponse")]
        System.Threading.Tasks.Task<GGNoTeam_V5.AccionesWS.listarAccionesPorFechasResponse> listarAccionesPorFechasAsync(GGNoTeam_V5.AccionesWS.listarAccionesPorFechasRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/")]
    public partial class accion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaField;
        
        private string horaField;
        
        private int idAccionField;
        
        private int idObjetoField;
        
        private string nombreActorField;
        
        private string tablaReferenciadaField;
        
        private string tipoAccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
                this.RaisePropertyChanged("hora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idAccion {
            get {
                return this.idAccionField;
            }
            set {
                this.idAccionField = value;
                this.RaisePropertyChanged("idAccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idObjeto {
            get {
                return this.idObjetoField;
            }
            set {
                this.idObjetoField = value;
                this.RaisePropertyChanged("idObjeto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombreActor {
            get {
                return this.nombreActorField;
            }
            set {
                this.nombreActorField = value;
                this.RaisePropertyChanged("nombreActor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tablaReferenciada {
            get {
                return this.tablaReferenciadaField;
            }
            set {
                this.tablaReferenciadaField = value;
                this.RaisePropertyChanged("tablaReferenciada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string tipoAccion {
            get {
                return this.tipoAccionField;
            }
            set {
                this.tipoAccionField = value;
                this.RaisePropertyChanged("tipoAccion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarAccion", WrapperNamespace="http://webservices.sist.afp.ggNoTeam/", IsWrapped=true)]
    public partial class insertarAccionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GGNoTeam_V5.AccionesWS.accion accion;
        
        public insertarAccionRequest() {
        }
        
        public insertarAccionRequest(GGNoTeam_V5.AccionesWS.accion accion) {
            this.accion = accion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarAccionResponse", WrapperNamespace="http://webservices.sist.afp.ggNoTeam/", IsWrapped=true)]
    public partial class insertarAccionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarAccionResponse() {
        }
        
        public insertarAccionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAccionesPorFechas", WrapperNamespace="http://webservices.sist.afp.ggNoTeam/", IsWrapped=true)]
    public partial class listarAccionesPorFechasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaIni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaFin;
        
        public listarAccionesPorFechasRequest() {
        }
        
        public listarAccionesPorFechasRequest(string fechaIni, string fechaFin) {
            this.fechaIni = fechaIni;
            this.fechaFin = fechaFin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAccionesPorFechasResponse", WrapperNamespace="http://webservices.sist.afp.ggNoTeam/", IsWrapped=true)]
    public partial class listarAccionesPorFechasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GGNoTeam_V5.AccionesWS.accion[] @return;
        
        public listarAccionesPorFechasResponse() {
        }
        
        public listarAccionesPorFechasResponse(GGNoTeam_V5.AccionesWS.accion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccionesWSChannel : GGNoTeam_V5.AccionesWS.AccionesWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccionesWSClient : System.ServiceModel.ClientBase<GGNoTeam_V5.AccionesWS.AccionesWS>, GGNoTeam_V5.AccionesWS.AccionesWS {
        
        public AccionesWSClient() {
        }
        
        public AccionesWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccionesWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccionesWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccionesWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GGNoTeam_V5.AccionesWS.insertarAccionResponse GGNoTeam_V5.AccionesWS.AccionesWS.insertarAccion(GGNoTeam_V5.AccionesWS.insertarAccionRequest request) {
            return base.Channel.insertarAccion(request);
        }
        
        public int insertarAccion(GGNoTeam_V5.AccionesWS.accion accion) {
            GGNoTeam_V5.AccionesWS.insertarAccionRequest inValue = new GGNoTeam_V5.AccionesWS.insertarAccionRequest();
            inValue.accion = accion;
            GGNoTeam_V5.AccionesWS.insertarAccionResponse retVal = ((GGNoTeam_V5.AccionesWS.AccionesWS)(this)).insertarAccion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GGNoTeam_V5.AccionesWS.insertarAccionResponse> GGNoTeam_V5.AccionesWS.AccionesWS.insertarAccionAsync(GGNoTeam_V5.AccionesWS.insertarAccionRequest request) {
            return base.Channel.insertarAccionAsync(request);
        }
        
        public System.Threading.Tasks.Task<GGNoTeam_V5.AccionesWS.insertarAccionResponse> insertarAccionAsync(GGNoTeam_V5.AccionesWS.accion accion) {
            GGNoTeam_V5.AccionesWS.insertarAccionRequest inValue = new GGNoTeam_V5.AccionesWS.insertarAccionRequest();
            inValue.accion = accion;
            return ((GGNoTeam_V5.AccionesWS.AccionesWS)(this)).insertarAccionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GGNoTeam_V5.AccionesWS.listarAccionesPorFechasResponse GGNoTeam_V5.AccionesWS.AccionesWS.listarAccionesPorFechas(GGNoTeam_V5.AccionesWS.listarAccionesPorFechasRequest request) {
            return base.Channel.listarAccionesPorFechas(request);
        }
        
        public GGNoTeam_V5.AccionesWS.accion[] listarAccionesPorFechas(string fechaIni, string fechaFin) {
            GGNoTeam_V5.AccionesWS.listarAccionesPorFechasRequest inValue = new GGNoTeam_V5.AccionesWS.listarAccionesPorFechasRequest();
            inValue.fechaIni = fechaIni;
            inValue.fechaFin = fechaFin;
            GGNoTeam_V5.AccionesWS.listarAccionesPorFechasResponse retVal = ((GGNoTeam_V5.AccionesWS.AccionesWS)(this)).listarAccionesPorFechas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GGNoTeam_V5.AccionesWS.listarAccionesPorFechasResponse> GGNoTeam_V5.AccionesWS.AccionesWS.listarAccionesPorFechasAsync(GGNoTeam_V5.AccionesWS.listarAccionesPorFechasRequest request) {
            return base.Channel.listarAccionesPorFechasAsync(request);
        }
        
        public System.Threading.Tasks.Task<GGNoTeam_V5.AccionesWS.listarAccionesPorFechasResponse> listarAccionesPorFechasAsync(string fechaIni, string fechaFin) {
            GGNoTeam_V5.AccionesWS.listarAccionesPorFechasRequest inValue = new GGNoTeam_V5.AccionesWS.listarAccionesPorFechasRequest();
            inValue.fechaIni = fechaIni;
            inValue.fechaFin = fechaFin;
            return ((GGNoTeam_V5.AccionesWS.AccionesWS)(this)).listarAccionesPorFechasAsync(inValue);
        }
    }
}
