//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGNoTeam_V5.MonitorOrdenWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", ConfigurationName="MonitorOrdenWS.MonitorOrdenWS")]
    public interface MonitorOrdenWS {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/helloRequest", ReplyAction="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/helloResponse")]
        GGNoTeam_V5.MonitorOrdenWS.helloResponse hello(GGNoTeam_V5.MonitorOrdenWS.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/helloRequest", ReplyAction="http://webservices.sist.afp.ggNoTeam/MonitorOrdenWS/helloResponse")]
        System.Threading.Tasks.Task<GGNoTeam_V5.MonitorOrdenWS.helloResponse> helloAsync(GGNoTeam_V5.MonitorOrdenWS.helloRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://webservices.sist.afp.ggNoTeam/", Order=0)]
        public GGNoTeam_V5.MonitorOrdenWS.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(GGNoTeam_V5.MonitorOrdenWS.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://webservices.sist.afp.ggNoTeam/", Order=0)]
        public GGNoTeam_V5.MonitorOrdenWS.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(GGNoTeam_V5.MonitorOrdenWS.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MonitorOrdenWSChannel : GGNoTeam_V5.MonitorOrdenWS.MonitorOrdenWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonitorOrdenWSClient : System.ServiceModel.ClientBase<GGNoTeam_V5.MonitorOrdenWS.MonitorOrdenWS>, GGNoTeam_V5.MonitorOrdenWS.MonitorOrdenWS {
        
        public MonitorOrdenWSClient() {
        }
        
        public MonitorOrdenWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonitorOrdenWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorOrdenWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorOrdenWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GGNoTeam_V5.MonitorOrdenWS.helloResponse GGNoTeam_V5.MonitorOrdenWS.MonitorOrdenWS.hello(GGNoTeam_V5.MonitorOrdenWS.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            GGNoTeam_V5.MonitorOrdenWS.helloRequest inValue = new GGNoTeam_V5.MonitorOrdenWS.helloRequest();
            inValue.Body = new GGNoTeam_V5.MonitorOrdenWS.helloRequestBody();
            inValue.Body.name = name;
            GGNoTeam_V5.MonitorOrdenWS.helloResponse retVal = ((GGNoTeam_V5.MonitorOrdenWS.MonitorOrdenWS)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GGNoTeam_V5.MonitorOrdenWS.helloResponse> GGNoTeam_V5.MonitorOrdenWS.MonitorOrdenWS.helloAsync(GGNoTeam_V5.MonitorOrdenWS.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<GGNoTeam_V5.MonitorOrdenWS.helloResponse> helloAsync(string name) {
            GGNoTeam_V5.MonitorOrdenWS.helloRequest inValue = new GGNoTeam_V5.MonitorOrdenWS.helloRequest();
            inValue.Body = new GGNoTeam_V5.MonitorOrdenWS.helloRequestBody();
            inValue.Body.name = name;
            return ((GGNoTeam_V5.MonitorOrdenWS.MonitorOrdenWS)(this)).helloAsync(inValue);
        }
    }
}
