//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGNoTeam_V5.TareasDiariasWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", ConfigurationName="TareasDiariasWS.TareasDiariasWS")]
    public interface TareasDiariasWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sist.afp.ggNoTeam/TareasDiariasWS/modificarTareaRequest", ReplyAction="http://webservices.sist.afp.ggNoTeam/TareasDiariasWS/modificarTareaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GGNoTeam_V5.TareasDiariasWS.modificarTareaResponse modificarTarea(GGNoTeam_V5.TareasDiariasWS.modificarTareaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sist.afp.ggNoTeam/TareasDiariasWS/modificarTareaRequest", ReplyAction="http://webservices.sist.afp.ggNoTeam/TareasDiariasWS/modificarTareaResponse")]
        System.Threading.Tasks.Task<GGNoTeam_V5.TareasDiariasWS.modificarTareaResponse> modificarTareaAsync(GGNoTeam_V5.TareasDiariasWS.modificarTareaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sist.afp.ggNoTeam/TareasDiariasWS/eliminarTareaRequest", ReplyAction="http://webservices.sist.afp.ggNoTeam/TareasDiariasWS/eliminarTareaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GGNoTeam_V5.TareasDiariasWS.eliminarTareaResponse eliminarTarea(GGNoTeam_V5.TareasDiariasWS.eliminarTareaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sist.afp.ggNoTeam/TareasDiariasWS/eliminarTareaRequest", ReplyAction="http://webservices.sist.afp.ggNoTeam/TareasDiariasWS/eliminarTareaResponse")]
        System.Threading.Tasks.Task<GGNoTeam_V5.TareasDiariasWS.eliminarTareaResponse> eliminarTareaAsync(GGNoTeam_V5.TareasDiariasWS.eliminarTareaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sist.afp.ggNoTeam/TareasDiariasWS/insertarTareaRequest", ReplyAction="http://webservices.sist.afp.ggNoTeam/TareasDiariasWS/insertarTareaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GGNoTeam_V5.TareasDiariasWS.insertarTareaResponse insertarTarea(GGNoTeam_V5.TareasDiariasWS.insertarTareaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sist.afp.ggNoTeam/TareasDiariasWS/insertarTareaRequest", ReplyAction="http://webservices.sist.afp.ggNoTeam/TareasDiariasWS/insertarTareaResponse")]
        System.Threading.Tasks.Task<GGNoTeam_V5.TareasDiariasWS.insertarTareaResponse> insertarTareaAsync(GGNoTeam_V5.TareasDiariasWS.insertarTareaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sist.afp.ggNoTeam/TareasDiariasWS/listarTareasPorEstadoPorItin" +
            "erarioRequest", ReplyAction="http://webservices.sist.afp.ggNoTeam/TareasDiariasWS/listarTareasPorEstadoPorItin" +
            "erarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GGNoTeam_V5.TareasDiariasWS.listarTareasPorEstadoPorItinerarioResponse listarTareasPorEstadoPorItinerario(GGNoTeam_V5.TareasDiariasWS.listarTareasPorEstadoPorItinerarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sist.afp.ggNoTeam/TareasDiariasWS/listarTareasPorEstadoPorItin" +
            "erarioRequest", ReplyAction="http://webservices.sist.afp.ggNoTeam/TareasDiariasWS/listarTareasPorEstadoPorItin" +
            "erarioResponse")]
        System.Threading.Tasks.Task<GGNoTeam_V5.TareasDiariasWS.listarTareasPorEstadoPorItinerarioResponse> listarTareasPorEstadoPorItinerarioAsync(GGNoTeam_V5.TareasDiariasWS.listarTareasPorEstadoPorItinerarioRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/")]
    public partial class tarea : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int estadoField;
        
        private string fechaCreacionField;
        
        private string fechaLimiteField;
        
        private int fidAutorField;
        
        private int fidItinerarioField;
        
        private int idTareaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fechaLimite {
            get {
                return this.fechaLimiteField;
            }
            set {
                this.fechaLimiteField = value;
                this.RaisePropertyChanged("fechaLimite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int fidAutor {
            get {
                return this.fidAutorField;
            }
            set {
                this.fidAutorField = value;
                this.RaisePropertyChanged("fidAutor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int fidItinerario {
            get {
                return this.fidItinerarioField;
            }
            set {
                this.fidItinerarioField = value;
                this.RaisePropertyChanged("fidItinerario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idTarea {
            get {
                return this.idTareaField;
            }
            set {
                this.idTareaField = value;
                this.RaisePropertyChanged("idTarea");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarTarea", WrapperNamespace="http://webservices.sist.afp.ggNoTeam/", IsWrapped=true)]
    public partial class modificarTareaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GGNoTeam_V5.TareasDiariasWS.tarea tarea;
        
        public modificarTareaRequest() {
        }
        
        public modificarTareaRequest(GGNoTeam_V5.TareasDiariasWS.tarea tarea) {
            this.tarea = tarea;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarTareaResponse", WrapperNamespace="http://webservices.sist.afp.ggNoTeam/", IsWrapped=true)]
    public partial class modificarTareaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarTareaResponse() {
        }
        
        public modificarTareaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTarea", WrapperNamespace="http://webservices.sist.afp.ggNoTeam/", IsWrapped=true)]
    public partial class eliminarTareaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTarea;
        
        public eliminarTareaRequest() {
        }
        
        public eliminarTareaRequest(int idTarea) {
            this.idTarea = idTarea;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTareaResponse", WrapperNamespace="http://webservices.sist.afp.ggNoTeam/", IsWrapped=true)]
    public partial class eliminarTareaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarTareaResponse() {
        }
        
        public eliminarTareaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTarea", WrapperNamespace="http://webservices.sist.afp.ggNoTeam/", IsWrapped=true)]
    public partial class insertarTareaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GGNoTeam_V5.TareasDiariasWS.tarea tarea;
        
        public insertarTareaRequest() {
        }
        
        public insertarTareaRequest(GGNoTeam_V5.TareasDiariasWS.tarea tarea) {
            this.tarea = tarea;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTareaResponse", WrapperNamespace="http://webservices.sist.afp.ggNoTeam/", IsWrapped=true)]
    public partial class insertarTareaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarTareaResponse() {
        }
        
        public insertarTareaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTareasPorEstadoPorItinerario", WrapperNamespace="http://webservices.sist.afp.ggNoTeam/", IsWrapped=true)]
    public partial class listarTareasPorEstadoPorItinerarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int fidItinerario;
        
        public listarTareasPorEstadoPorItinerarioRequest() {
        }
        
        public listarTareasPorEstadoPorItinerarioRequest(int estado, int fidItinerario) {
            this.estado = estado;
            this.fidItinerario = fidItinerario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTareasPorEstadoPorItinerarioResponse", WrapperNamespace="http://webservices.sist.afp.ggNoTeam/", IsWrapped=true)]
    public partial class listarTareasPorEstadoPorItinerarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sist.afp.ggNoTeam/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GGNoTeam_V5.TareasDiariasWS.tarea[] @return;
        
        public listarTareasPorEstadoPorItinerarioResponse() {
        }
        
        public listarTareasPorEstadoPorItinerarioResponse(GGNoTeam_V5.TareasDiariasWS.tarea[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TareasDiariasWSChannel : GGNoTeam_V5.TareasDiariasWS.TareasDiariasWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TareasDiariasWSClient : System.ServiceModel.ClientBase<GGNoTeam_V5.TareasDiariasWS.TareasDiariasWS>, GGNoTeam_V5.TareasDiariasWS.TareasDiariasWS {
        
        public TareasDiariasWSClient() {
        }
        
        public TareasDiariasWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TareasDiariasWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TareasDiariasWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TareasDiariasWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GGNoTeam_V5.TareasDiariasWS.modificarTareaResponse GGNoTeam_V5.TareasDiariasWS.TareasDiariasWS.modificarTarea(GGNoTeam_V5.TareasDiariasWS.modificarTareaRequest request) {
            return base.Channel.modificarTarea(request);
        }
        
        public int modificarTarea(GGNoTeam_V5.TareasDiariasWS.tarea tarea) {
            GGNoTeam_V5.TareasDiariasWS.modificarTareaRequest inValue = new GGNoTeam_V5.TareasDiariasWS.modificarTareaRequest();
            inValue.tarea = tarea;
            GGNoTeam_V5.TareasDiariasWS.modificarTareaResponse retVal = ((GGNoTeam_V5.TareasDiariasWS.TareasDiariasWS)(this)).modificarTarea(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GGNoTeam_V5.TareasDiariasWS.modificarTareaResponse> GGNoTeam_V5.TareasDiariasWS.TareasDiariasWS.modificarTareaAsync(GGNoTeam_V5.TareasDiariasWS.modificarTareaRequest request) {
            return base.Channel.modificarTareaAsync(request);
        }
        
        public System.Threading.Tasks.Task<GGNoTeam_V5.TareasDiariasWS.modificarTareaResponse> modificarTareaAsync(GGNoTeam_V5.TareasDiariasWS.tarea tarea) {
            GGNoTeam_V5.TareasDiariasWS.modificarTareaRequest inValue = new GGNoTeam_V5.TareasDiariasWS.modificarTareaRequest();
            inValue.tarea = tarea;
            return ((GGNoTeam_V5.TareasDiariasWS.TareasDiariasWS)(this)).modificarTareaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GGNoTeam_V5.TareasDiariasWS.eliminarTareaResponse GGNoTeam_V5.TareasDiariasWS.TareasDiariasWS.eliminarTarea(GGNoTeam_V5.TareasDiariasWS.eliminarTareaRequest request) {
            return base.Channel.eliminarTarea(request);
        }
        
        public int eliminarTarea(int idTarea) {
            GGNoTeam_V5.TareasDiariasWS.eliminarTareaRequest inValue = new GGNoTeam_V5.TareasDiariasWS.eliminarTareaRequest();
            inValue.idTarea = idTarea;
            GGNoTeam_V5.TareasDiariasWS.eliminarTareaResponse retVal = ((GGNoTeam_V5.TareasDiariasWS.TareasDiariasWS)(this)).eliminarTarea(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GGNoTeam_V5.TareasDiariasWS.eliminarTareaResponse> GGNoTeam_V5.TareasDiariasWS.TareasDiariasWS.eliminarTareaAsync(GGNoTeam_V5.TareasDiariasWS.eliminarTareaRequest request) {
            return base.Channel.eliminarTareaAsync(request);
        }
        
        public System.Threading.Tasks.Task<GGNoTeam_V5.TareasDiariasWS.eliminarTareaResponse> eliminarTareaAsync(int idTarea) {
            GGNoTeam_V5.TareasDiariasWS.eliminarTareaRequest inValue = new GGNoTeam_V5.TareasDiariasWS.eliminarTareaRequest();
            inValue.idTarea = idTarea;
            return ((GGNoTeam_V5.TareasDiariasWS.TareasDiariasWS)(this)).eliminarTareaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GGNoTeam_V5.TareasDiariasWS.insertarTareaResponse GGNoTeam_V5.TareasDiariasWS.TareasDiariasWS.insertarTarea(GGNoTeam_V5.TareasDiariasWS.insertarTareaRequest request) {
            return base.Channel.insertarTarea(request);
        }
        
        public int insertarTarea(GGNoTeam_V5.TareasDiariasWS.tarea tarea) {
            GGNoTeam_V5.TareasDiariasWS.insertarTareaRequest inValue = new GGNoTeam_V5.TareasDiariasWS.insertarTareaRequest();
            inValue.tarea = tarea;
            GGNoTeam_V5.TareasDiariasWS.insertarTareaResponse retVal = ((GGNoTeam_V5.TareasDiariasWS.TareasDiariasWS)(this)).insertarTarea(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GGNoTeam_V5.TareasDiariasWS.insertarTareaResponse> GGNoTeam_V5.TareasDiariasWS.TareasDiariasWS.insertarTareaAsync(GGNoTeam_V5.TareasDiariasWS.insertarTareaRequest request) {
            return base.Channel.insertarTareaAsync(request);
        }
        
        public System.Threading.Tasks.Task<GGNoTeam_V5.TareasDiariasWS.insertarTareaResponse> insertarTareaAsync(GGNoTeam_V5.TareasDiariasWS.tarea tarea) {
            GGNoTeam_V5.TareasDiariasWS.insertarTareaRequest inValue = new GGNoTeam_V5.TareasDiariasWS.insertarTareaRequest();
            inValue.tarea = tarea;
            return ((GGNoTeam_V5.TareasDiariasWS.TareasDiariasWS)(this)).insertarTareaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GGNoTeam_V5.TareasDiariasWS.listarTareasPorEstadoPorItinerarioResponse GGNoTeam_V5.TareasDiariasWS.TareasDiariasWS.listarTareasPorEstadoPorItinerario(GGNoTeam_V5.TareasDiariasWS.listarTareasPorEstadoPorItinerarioRequest request) {
            return base.Channel.listarTareasPorEstadoPorItinerario(request);
        }
        
        public GGNoTeam_V5.TareasDiariasWS.tarea[] listarTareasPorEstadoPorItinerario(int estado, int fidItinerario) {
            GGNoTeam_V5.TareasDiariasWS.listarTareasPorEstadoPorItinerarioRequest inValue = new GGNoTeam_V5.TareasDiariasWS.listarTareasPorEstadoPorItinerarioRequest();
            inValue.estado = estado;
            inValue.fidItinerario = fidItinerario;
            GGNoTeam_V5.TareasDiariasWS.listarTareasPorEstadoPorItinerarioResponse retVal = ((GGNoTeam_V5.TareasDiariasWS.TareasDiariasWS)(this)).listarTareasPorEstadoPorItinerario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GGNoTeam_V5.TareasDiariasWS.listarTareasPorEstadoPorItinerarioResponse> GGNoTeam_V5.TareasDiariasWS.TareasDiariasWS.listarTareasPorEstadoPorItinerarioAsync(GGNoTeam_V5.TareasDiariasWS.listarTareasPorEstadoPorItinerarioRequest request) {
            return base.Channel.listarTareasPorEstadoPorItinerarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<GGNoTeam_V5.TareasDiariasWS.listarTareasPorEstadoPorItinerarioResponse> listarTareasPorEstadoPorItinerarioAsync(int estado, int fidItinerario) {
            GGNoTeam_V5.TareasDiariasWS.listarTareasPorEstadoPorItinerarioRequest inValue = new GGNoTeam_V5.TareasDiariasWS.listarTareasPorEstadoPorItinerarioRequest();
            inValue.estado = estado;
            inValue.fidItinerario = fidItinerario;
            return ((GGNoTeam_V5.TareasDiariasWS.TareasDiariasWS)(this)).listarTareasPorEstadoPorItinerarioAsync(inValue);
        }
    }
}
